version: '3'
services:
  server:
    image: 'python:3.8-slim'
    ports:
      - '14208:14208'
    volumes:
      - '.:/app'
    working_dir: '/app'
    command: ['./run.sh']

  update:
    image: 'python:3.8-slim'
    volumes:
      - '.:/app'
    working_dir: '/app'
    command: ['./update.sh']